config/routes.rb
Rails.application.routes.draw do
  root 'articles#index'

  resources :articles do
  	member do
  		post 'like'
  	end
  end

  resources :users, except: [:new]
  get '/register', to: 'users#new'
  
  resources :tags

  get '/login', to: 'logins#new'
  post '/login', to: 'logins#create'
  get '/logout', to: 'logins#destroy'

end

app/models/article.rb
class Article < ActiveRecord::Base

	has_many :articles_tags
	has_many :tags, through: :articles_tags

	
	belongs_to :user
	has_many :likes
	
	validates :title, presence: true, length:{minimum: 10, maximum: 200}
	validates :body, presence: true, length:{minimum: 25, maximum: 1500}

	validates :user_id, presence: true

	def likes_total
		self.likes.where(like: true).size
	end

	def dislikes_total
		self.likes.where(like: false).size
	end


	#for carrierwave
	mount_uploader :image, ImageUploader

	#image validation
	validate :image_size

	private 
		def image_size
			if image.size > 5.megabytes
				error.add(:image, "should be lessthan 5MB")
			end 
		end
end

app/models/articles_tag.rb
class ArticlesTag < ActiveRecord::Base
	belongs_to :article 
	belongs_to :tag
end

app/models/like.rb
class Like < ActiveRecord::Base
	belongs_to :article
	belongs_to :user

	validates :user_id, presence: true
	validates :article_id, presence: true

	validates_uniqueness_of :user, scope: :article
end

app/models/role.rb
class Role < ActiveRecord::Base
	has_many :users
end

app/models/tag.rb
class Tag < ActiveRecord::Base
	has_many :articles_tags
	has_many :articles, through: :articles_tags
end

app/models/user.rb
class User < ActiveRecord::Base
	
	has_many :articles, dependent: :destroy
	belongs_to :role

	validates :name, presence: true, length:{minimum: 3, maximum: 25}
	validates :desc, length:{minimum: 15, maximum: 100 }

	VALID_EMAIL_REGEX = /\A[\w+\1-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	before_save {self.email = email.downcase}
	validates :email, presence: true, uniqueness: {case_sensitive: false}, length: { maximum: 105 }, format: { with: VALID_EMAIL_REGEX }
	
	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?


  def current_user
  	#if session exists - find user who has hash user_id - if found
  	#it will return the user or false
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
  	!!current_user
  end

  # will be use only in controller
  def require_user
  	if !logged_in? 
  		flash[:danger] = "You must be logged in"
  		redirect_to :root
  	end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy, :like]
  before_action :require_user, except: [:show, :index]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  
  def index
    @articles = Article.all
  end

  def show
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article }
        format.json { render :show, status: :created, location: @article }
        flash[:success] = "Article added successfully"
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article }
        format.json { render :show, status: :ok, location: @article }
        flash[:success] = "Article updated successfully"
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url }
      format.json { head :no_content }
      flash[:danger] = "Article deleted successfully"
    end
  end

  def like

    valid_user = @article.likes.find_by(user: current_user)

    if valid_user

      like = @article.likes.find_by(user: current_user)

      if like.like
        like.like = false
        flash[:success] = "Changed to dislike"
      elsif !like.like
        like.like = true
        flash[:success] = "Changed to like"
      end

      like.save

    else

      like = Like.create(like: params[:like], user: current_user, article: @article)
        
        if like.valid?
          flash[:success] = "Liked Successfully"
        else
          flash[:danger]= "oops!! Somthing went wrong."
        end

    end

    redirect_to :back
  end

  private
  
    def set_article
      @article = Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:title, :body, :image)
    end

    def require_same_user
      if current_user != @article.user
        flash[:danger] = "You can only edit your articles !!"
        redirect_to articles_path
      end
    end
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController

	def new 
	end

	def create
		user = User.find_by(email: params[:email])

		if user and user.authenticate(params[:password])
			session[:user_id] = user.id
			flash[:success] = "Welcome"
		else
			flash[:danger]="email or password is not correct"
		end
		redirect_to articles_path
	end


	def destroy
		session[:user_id]=nil
		flash[:success] = "logged out"
		redirect_to root_path
	end
	
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def index
	end 
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
	
	def index
	end

	def new
	end
	
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_same_user, except: [:show, :index]

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
        session[:user_id] = @user.id
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
      session[:user_id] = nil
    end
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name, :desc, :email, :password)
    end

    def require_same_user
      if current_user != @user
        flash[:danger]="Not Allowed"
        redirect_to users_path
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>


<%= form_for(@article, html: {multipart: true}) do |f| %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div>
  <%= f.file_field :image, accept: 'image/jpeg,image/gif,image/png' %>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<script type="text/javascript">
  $('#article_image').bind('change', function(){
    size_in_megabytes = this.files[0].size/1024/1024;
    if(size_in_megabytes > 5){
      alert("maximum file size is 5mb");
    }
  });
</script>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>


  <% @articles.each do |article| %>

      <div class="blog">

        <% if article.image? %>
        <div class="picture">
            <div class="profile-pic">
              <%= link_to('') do %>
                <img src="img/person.png">
                <h2><%= article.user.name %></h2>
              <% end %>
            </div>

            <%= image_tag(article.image.url, class: "background-img")%>
            </div>
          <% end %>
          
        
          <div class="blog-text">
            <div class="blog-title">
               <h1><%= link_to article.title, article %></h1>
            </div>
            <div class="blog-body">
              <p><%= truncate(article.body, length: 300 ) %></p>
            </div>
          

            <div class="tag-btns">
               <%= render article.tags %>
            </div>

            <hr class="blog-border">

            <div class="stat">
              <a href="#" class="stat-left"><%= article.created_at %></a>
            <%= link_to(like_article_path(article, like: true), method: :post, class: "stat-right") do %> <i class="fa  fa-heart-o"></i> <%= article.likes_total %> likes <% end %>
            </div>

            <% if logged_in? %>
            <div class="options-bar">
             <p>
               <%= link_to 'Edit', edit_article_path(article) %>
              <%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %>
             </p>
             </div>
         <% end %>
          
          </div>

        </div>


  <% end %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

		<div class="blog">

        <% if @article.image? %>
        <div class="picture">
            <div class="profile-pic">
              <%= link_to('') do %>
                <img src="img/person.png">
                <h2><%= @article.user.name %></h2>
              <% end %>
            </div>

            <%= image_tag(@article.image.url, class: "background-img")%>
            </div>
          <% end %>
          
        
          <div class="blog-text">
            <div class="blog-title">
               <h1><%= @article.title %></h1>
            </div>
            <div class="blog-body">
              <p><%= simple_format(@article.body) %></p>
            </div>
          

            <div class="tag-btns">
               <%= render @article.tags %>
            </div>

            <hr class="blog-border">

            <div class="stat">
              <a href="#" class="stat-left"><%= @article.created_at %></a>
            <%= link_to(like_article_path(@article, like: true), method: :post, class: "stat-right") do %> <i class="fa  fa-heart-o"></i> <%= @article.likes_total %> likes <% end %>
            </div>

            <% if logged_in? %>
            <div class="options-bar">
             <p>
               <%= link_to 'Edit', edit_article_path(@article) %>
              <%= link_to 'Destroy', @article, method: :delete, data: { confirm: 'Are you sure?' } %>
             </p>
             </div>
         <% end %>
          
          </div>

        </div>

app/views/layouts/_messages.html.erb
<% flash.each do |message_type, message| %>
	
	<div class="msg">
		<p><%= message %> <p>
	</div>
<% end %>

app/views/layouts/_nav.html.erb
				
<div class="section group">

	<div class="col span_1_of_1">
		<%= link_to "Loza Blog", root_path, class: "title" %>	
		<div class="title-border"></div>
	</div>
</div>

<div class="section group">

	<div class="col span_1_of_1">
		<p class="content">A simple, notebook inspired, theme for Ghost. Includes four colour schemes to kick start your customisation.
		</p>
		<div class="content-border"></div>

	</div>
</div>

<div class="section group">

	<div class="col span_1_of_1">
		<ul class="nav">
			<% if logged_in? %>
			<li><%= link_to "New Article", new_article_path %> 
			<% end %>

			<li><%= link_to "Articles", articles_path %></li>
			<li><%= link_to "Users", users_path %>

			<% if logged_in? %></li>
				<li><%= link_to "Logout", logout_path %></li>
			<% end %>

			<% if !logged_in? %>
				<li><%= link_to "Login", login_path %></li>
				<li><%= link_to "Sign Up", register_path %></li>
				</li>
			<% end %>
		</ul>
		<div class="nav-border"></div>
	</div>
</div>

<div class="section group">

	<div class="col span_1_of_1 social-links">
		<a href="#"><i class="fa fa-twitter"></i></a>
		<a href="#"><i class="fa fa-github"></i></a>
		<a href="#"><i class="fa fa-dribbble"></i></a>
	</div>
</div>

<div class="section group">

	<div class="col span_1_of_1 copyright">
		<a href="www.zulucoding.com">blog by zulucoding</a>		
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LozaBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<div class="wrapper">
			
			<div class="section group">

				<div class="col span_1_of_3">
				<div class="section group">
				<!-- LEFT SIDE -->
				<%= render 'layouts/nav' %>
				</div>
				</div>

				<!-- RIGHT SIDE -->
				<div class="col span_2_of_3">
				<div class="section group">
				<%= render 'layouts/messages' %>
				<%= yield %>
				</div>
				</div>

			</div>

			<%= render 'layouts/footer' %>

	</div>

</body>
</html>

app/views/logins/_form.html.erb
<%= form_tag '/login' do %>

	<p><%= label_tag :email %>
	<%= text_field_tag :email %></p>

	<p><%= label_tag :password %>
	<%= password_field_tag :password %></p>

	<p><%= submit_tag 'Login' %></p>

<% end %>

app/views/logins/new.html.erb
<%= render 'shared/title', title: "Login" %>

<%= render 'form' %>

app/views/pages/index.html.erb
<h1> Home </h1>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>

	<div class="row">
		<div class="alert alert-danger col-md-8 col-md-offset-2">
		<h5> please correct the following errors</h5>
		<ul>
			<% obj.errors.full_messages.each do |msg| %>
			<li> <%= msg %> </li>
			<% end %>
		</ul>
	</div>

<%end%>

app/views/shared/_title.html.erb
<h1> <%= title %> </h1>

app/views/tags/_tag.html.erb
<button class="btn"><%= tag.name %></button>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user%>

<%= form_for @user do |f| %>

	<%= f.label :name, "Username" %>
	<%= f.text_field :name %>

	<%= f.label :desc, "Description" %>
	<%= f.text_field :desc %>

	<%= f.label :email, "Email" %>
	<%= f.text_field :email %>

	<%= f.label :password, "Password" %>
	<%= f.password_field :password %>

	<%= f.submit("Submit") %>

<% end %>

app/views/users/edit.html.erb
<%= render 'shared/title', title: "Edit User" %>

<%= render 'form' %>

app/views/users/index.html.erb
<h1> All Users </h1>

<% @users.all.each do |user| %>
	<h3> <%= user.name %></h3>
	<p> <%= user.desc %> </p>
	<p> <%= link_to "show", user_path(user) %> - <%= link_to "Edit", edit_user_path(user) %> -
	<%= link_to "Delete", user, method: :delete %>
<% end %>

<p><%= link_to "home", root_path %></p>

app/views/users/new.html.erb
<%= render 'shared/title', title: "New User" %>

<%= render 'form' %>

app/views/users/show.html.erb
<%= render 'shared/title', title: "#{@user.name}" %>

<p> <%= @user.desc %> </p>

<p> <%= link_to "users list", users_path %>